### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by sintezcs** [m5stack/M5CoreS3#12]
ESP32-S3 supports Bluetooth. Can I work with Bluetooth on M5CoreS3? Fore some reason it's not mentioned anywhere in the specs.

**Comment by LindsayReid** [comment]
I certainly hope so as that's something I want to do. I also thought it strange it wasn't mentioned. Whilst we're still waiting for any way to programme using MFlow, Bluetooth does seem to be shown as a feature. Let's hope!

**Comment by IcingTomato** [comment]
Bluetooth is available. It is the same as the normal ESP32.
