### ISSUE TITLE
Failing to compile due to missing file "bmi270.h"

### ISSUE THREAD

**Issue by tinytaro** [m5stack/M5CoreS3#2]
Run `pio run` command:

```
Archiving .pio\build\esp32-s3-devkitc-1\libd4a\libSPI.a
Compiling .pio\build\esp32-s3-devkitc-1\FrameworkArduino\HWCDC.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\FrameworkArduino\HardwareSerial.cpp.o
In file included from src/utility/I2C_IMU.cpp:1:
src/utility/I2C_IMU.h:7:10: fatal error: bmi270.h: No such file or directory

****************************************************************
* Looking for bmi270.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:bmi270.h"
* Web  > https://registry.platformio.org/search?q=header:bmi270.h
*
****************************************************************

 #include "bmi270.h"
          ^~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32-s3-devkitc-1\src\utility\I2C_IMU.cpp.o] Error 1
In file included from src/M5CoreS3.h:16,
                 from src/M5CoreS3.cpp:5:
src/utility/I2C_IMU.h:7:10: fatal error: bmi270.h: No such file or directory
```

**Comment by IcingTomato** [comment]
OK, I will test it.

**Comment by Tinyu-Zhao** [comment]
Temporary solution, follow the links to install both libraries manually

https://github.com/boschsensortec/BMI270-Sensor-API

https://github.com/BoschSensortec/BMM150-Sensor-API

**Comment by tunefs** [comment]
I have installed these. Now I get another error.
```
/Users/saito/Documents/Arduino/libraries/M5CoreS3/src/utility/I2C_IMU.cpp: In member function 'void I2C_IMU::Update()':
/Users/saito/Documents/Arduino/libraries/M5CoreS3/src/utility/I2C_IMU.cpp:135:13: error: 'bmm150_aux_raw_mag_data' was not declared in this scope
             bmm150_aux_raw_mag_data(bmi_sensor_data.aux_data, &bmm_mag_data,
             ^~~~~~~~~~~~~~~~~~~~~~~
/Users/saito/Documents/Arduino/libraries/M5CoreS3/src/utility/I2C_IMU.cpp:135:13: note: suggested alternative: 'bmm150_aux_mag_data'
             bmm150_aux_raw_mag_data(bmi_sensor_data.aux_data, &bmm_mag_data,
             ^~~~~~~~~~~~~~~~~~~~~~~
             bmm150_aux_mag_data
```

**Comment by wianoski** [comment]
got this error too 
![image](https://github.com/m5stack/M5CoreS3/assets/20513613/97e6b38b-3084-4d27-b9ba-dc4b865161bc)

**Comment by 3110** [comment]
The following code can be used to compile this library.
https://github.com/imliubo/CoreS3-UserDemo/tree/main/lib/BMM150-Sensor-API
https://github.com/imliubo/CoreS3-UserDemo/tree/main/lib/BMI270-Sensor-API

**Comment by Tinyu-Zhao** [comment]
Please install this repository and try to compile again.
@3110 @tunefs @tinytaro @wianoski

**Comment by tunefs** [comment]
I was able to build it successfully and it works on Core S3. Thank you very much.

**Comment by 3110** [comment]
@Tinyu-Zhao Could you add the following in `platformio.ini`?
``
lib_deps =
    https://github.com/Tinyu-Zhao/BMI270_Sensor
```

**Comment by Tinyu-Zhao** [comment]
> The following code can be used to compile this library.
> https://github.com/imliubo/CoreS3-UserDemo/tree/main/lib/BMM150-Sensor-API
> https://github.com/imliubo/CoreS3-UserDemo/tree/main/lib/BMI270-Sensor-API

Added to platform.ini
