### ISSUE TITLE
Fail to build HelloWorld.ino: Compilation error: 'USBSerial' was not declared in this scope

### ISSUE THREAD

**Issue by lboue** [m5stack/M5CoreS3#21]
Hello,

It looks like a line is missing to declare the variable in [HelloWorld.ino](https://github.com/m5stack/M5CoreS3/blob/main/examples/Basics/HelloWorld/HelloWorld.ino) example: 

```
C:\Users\user\AppData\Local\Temp\.arduinoIDE-unsaved2023430-5812-sfr3mr.33j4\HelloWorld\HelloWorld.ino:32:5: error: 'USBSerial' was not declared in this scope
     USBSerial.println(
     ^~~~~~~~~
C:\Users\user\AppData\Local\Temp\.arduinoIDE-unsaved2023430-5812-sfr3mr.33j4\HelloWorld\HelloWorld.ino:32:5: note: suggested alternative: 'Serial'
     USBSerial.println(
     ^~~~~~~~~
     Serial

exit status 1

Compilation error: 'USBSerial' was not declared in this scope
```

**Comment by felmue** [comment]
Hello @lboue 

have you selected the correct board? One which is an **S3** variant of the ESP32?

Thanks
Felix

**Comment by lboue** [comment]
> Hello @lboue
> 
> have you selected the correct board? One which is an **S3** variant of the ESP32?
> 
> Thanks Felix

Yes I did. I selected "M5Stack-CoreS3.

![image](https://github.com/m5stack/M5CoreS3/assets/938089/2d4177e3-3706-45be-b99b-a5a489a6debb)

**Comment by lboue** [comment]
Here is the menu:
![image](https://github.com/m5stack/M5CoreS3/assets/938089/c3e29dc9-a627-4d4a-b64c-0d63dd34f263)

**Comment by felmue** [comment]
Hello @lboue 

hmm, ok. Then I am afraid I don't know why it fails to compile. Sorry.

Thanks
Felix

**Comment by felmue** [comment]
Hello @lboue 

hmm ok. I am afraid I don't know why the compilation fails then. Sorry.

Thanks
Felix

**Comment by lboue** [comment]
It must be is an issue with the code because serial port works fine with this example code with no includes:
```
void setup() {
  Serial.begin(9600);

  Serial.println("SERIAL");
  delay(500);
}

void loop() {
  // basic readout test, just print the current temp
  
  Serial.print("SERIAL"); 
  delay(1000);
}
```

![image](https://github.com/m5stack/M5CoreS3/assets/938089/e3b59511-8879-41e9-8c03-95e3110258b0)

**Comment by lboue** [comment]
This example works when I replace USBSerial by Serial in the included files. See my PR.

**Comment by Tinyu-Zhao** [comment]
You need to select this.
<img width="650" alt="image" src="https://github.com/m5stack/M5CoreS3/assets/44396641/a2535b93-13bb-4f34-b66d-505f7910edfb">
