### ISSUE TITLE
[Request] Add Basics/speak example for CoreS3

### ISSUE THREAD

**Issue by lboue** [m5stack/M5CoreS3#25]
Hello,

Could you add this [Basics/speak](https://github.com/m5stack/M5Core2/blob/master/examples/Basics/speak/speak.ino) example's equivalent of the Core2 card for the CoreS3 kit?

Regards

**Comment by IcingTomato** [comment]
@Tinyu-Zhao

**Comment by YonatanAmir1996** [comment]
Hi @IcingTomato, I hope you're doing well. It's been two months since we last discussed the support feature. Would you be able to add it? Thanks for considering!

**Comment by IcingTomato** [comment]
> Hi @IcingTomato, I hope you're doing well. It's been two months since we last discussed the support feature. Would you be able to add it? Thanks for considering!

![image](https://github.com/m5stack/M5CoreS3/assets/24474531/ea6f728e-4001-4729-813d-0006d85d8fee)

**Comment by YonatanAmir1996** [comment]
> Hi @IcingTomato, I hope you're doing well. It's been two months since we last discussed the support feature. Would you be able to add it? Thanks for considering!

@Tinyu-Zhao

**Comment by Tinyu-Zhao** [comment]
You can try this program, the function on line 72 is used to generate the audio, you can also replace the audio with another one.
[cores3-speaker-master.zip](https://github.com/m5stack/M5CoreS3/files/12515124/cores3-speaker-master.zip)
