### ISSUE TITLE
[Request] Add Factory Test code to the repo

### ISSUE THREAD

**Issue by markwjkelly** [m5stack/M5CoreS3#26]
Are you planning on adding the Factory Test code to the Repo.  That has always been a great addition to all your dev kits, especially as it helps developers get a better understanding of the complete system.

**Comment by luisllamasbinaburo** [comment]
I restore Factory Test and create a PR.
While we wait for it to be accepted, you can have the code here https://github.com/luisllamasbinaburo/M5CoreS3

**Comment by Tinyu-Zhao** [comment]
> Are you planning on adding the Factory Test code to the Repo. That has always been a great addition to all your dev kits, especially as it helps developers get a better understanding of the complete system.

Factory test program is too large, will cause the download time to extend many times, you can refer to this repository.

**Comment by luisllamasbinaburo** [comment]
Maybe you can create a different repo for M5StackCoreS3 Factory Demo?
Like you do, for example, for de M5Paper? https://github.com/m5stack/M5Paper_FactoryTest

**Comment by Tinyu-Zhao** [comment]
> Maybe you can create a different repo for M5StackCoreS3 Factory Demo?
> 
> Like you do, for example, for M5Paper? https://github.com/m5stack/M5Paper_FactoryTest

Ok，I will.
