### ISSUE TITLE
uiflow?

### ISSUE THREAD

**Issue by d4rkdpg** [m5stack/M5CoreS3#3]
How I flash uiflow onto this, i just received a batch of them :). And I wanted to migrate my core2 projects to this?

**Comment by imliubo** [comment]
Hi @d4rkdpg , cores3 uiflow support is not fully ready, and we develop new uiflow to support esp32-s3 chips device, you can check [here](https://uiflow2.m5stack.com/) but still in alpha version, cores3 support almost ready.

**Comment by d4rkdpg** [comment]
how can I add to apha version, I dont see how?

**Comment by imliubo** [comment]
> how can I add to alpha version, I dont see how? 

CoreS3 FW is not release yet.

> also alpha version looks to be missing a lot of stuff like remote+, lorawan intergration etc.

Yeah, uiflow 2.0 has big change, module and unit we are supporting now, we will support all module and unit ASAP.

**Comment by d4rkdpg** [comment]
Can I asked when this will be? I need the asap for production.  also atoms3 lite I need all features of uiflow1.

**Comment by d4rkdpg** [comment]
I haven't see much progress here thanks for uiflow 2 support, but we need some ui buttons, sliders, remote plus support, lora module support etc.  it's really unusable

**Comment by pgsinoz** [comment]
will it include 8encoder module too?

**Comment by pgsinoz** [comment]
> will it include 8encoder module too?

confirming this is now fixed in V2.00 Alpha 19 thanks

**Comment by Tinyu-Zhao** [comment]
> > will it include 8encoder module too?它会包括 8 个编码器模块吗？
> 
> confirming this is now fixed in V2.00 Alpha 19 thanks确认这在 V2.00 Alpha 19 中已修复，谢谢

Closed.
