### ISSUE TITLE
Dependency on BMI Sensor

### ISSUE THREAD

**Issue by pgsinoz** [m5stack/M5CoreS3#34]
I finally got the Hello World example to compile.
I needed to add the library for CoreS3 and all its dependencies
Then after that add the library for the BMI Sensor 270 - should be marked as a dependency.

Also fixed some typos referring to AtomS3 in the Readme files.

Hmmmm, is this product ready for release!

**Comment by Tinyu-Zhao** [comment]
Thanks for the tip, I have established a connection to the BMI Sensor 270 library.
