### ISSUE TITLE
Sample request: source code of the M5CoreS3 factory firmware

### ISSUE THREAD

**Issue by hpsaturn** [m5stack/M5CoreS3#38]
## Overview

The application demo or Factory firmware of this new M5CoreS3 is really nice, awesome job guys. Maybe is possible have it? Thanks in advance.

**Comment by Tinyu-Zhao** [comment]
A repository on Github will follow.
[CoreS3-UserDemo.zip](https://github.com/m5stack/M5CoreS3/files/12116077/CoreS3-UserDemo.zip)
