### ISSUE TITLE
IMU Error

### ISSUE THREAD

**Issue by DMDAYAANKHAN** [m5stack/M5CoreS3#44]
In file included from /Users/x/Documents/Arduino/libraries/M5CoreS3/src/M5CoreS3.h:16,
                 from /Users/x/Documents/DATA 27 May 2023/Arduino/M5_2/M5_2.ino:1:
/Users/x/Documents/Arduino/libraries/M5CoreS3/src/utility/I2C_IMU.h:6:10: fatal error: BMI270_Sensor.h: No such file or directory
 #include "BMI270_Sensor.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by Tinyu-Zhao** [comment]
Pls install this library.
## Depend Libraries:
  - [BMI270_Sensor](https://github.com/Tinyu-Zhao/BMI270_Sensor)
