### ISSUE TITLE
Touch example .ino

### ISSUE THREAD

**Issue by jaylfc** [m5stack/M5CoreS3#49]
Can we get an example multifunction sketch showing us how to use screen/touch/sd card etc simultaneously. I'm struggling to get the features I need working together with the limited resources.

**Comment by felmue** [comment]
Hello @jaylfc 

have you checked out the Touch [example](https://github.com/m5stack/M5Unified/blob/master/examples/Basic/Touch/Touch.ino) in the Unified repository? It shows how to use screen and touch. For the SD card maybe check out this [example](https://github.com/m5stack/M5Unified/blob/master/examples/Advanced/Speaker_SD_wav_file/Speaker_SD_wav_file.ino).

Thanks
Felix

**Comment by jaylfc** [comment]
I have thanks ,they helped a little!
