### ISSUE TITLE
Compilation error: 'USBSerial' was not declared in this scope

### ISSUE THREAD

**Issue by ropg** [m5stack/M5CoreS3#50]
I use the Arduino IDE (v.2.2.1) and have M5Stack board manager 2.0.8 and M5CoreS3 library v0.0.4

When I try to compile HelloWorld.ino from the examples directory, I get:
    Compilation error: 'USBSerial' was not declared in this scope

<img width="1954" alt="image" src="https://github.com/m5stack/M5CoreS3/assets/343196/a18559f9-49b5-4e8b-be0a-3a275c14c24f">

When I comment out the SerialUSB statement in the example, the compiler now complains about USBSerial in the I2C_IMU library.

<img width="1372" alt="image" src="https://github.com/m5stack/M5CoreS3/assets/343196/99e0cdb6-ca7b-4217-bd2f-a28aecac4fbf">

&nbsp;

None of examples seem to compile, so I must be doing something wrong.

**Comment by ylabo0717** [comment]
@ropg I also encountered the same problem, but I was able to resolve it by uninstalling V0.0.4 and installing the latest revision.

The following revision appears to have fixed the problem.
https://github.com/m5stack/M5CoreS3/commit/a9187b74aa3d6c90cc2cfc8f7e6d466ae3dd6cd7

Below is the procedure I have tried. I hope this will be helpful.

## 1. Uninstall V0.0.4

Remove V0.04 in Library Manager.

![image](https://github.com/m5stack/M5CoreS3/assets/243476/e8aae5f6-8f04-40e5-9727-17c2f59ab1a2)

## 2. Download zip

Download the latest revision from this repository.

![image](https://github.com/m5stack/M5CoreS3/assets/243476/e2bc4ced-410c-4315-b3fb-6c0ba550c7a6)

## 3. Install the zip to Arduino IDE

Select menu. Sketch -> Include Library -> Add .ZIP Library

![image](https://github.com/m5stack/M5CoreS3/assets/243476/9b1d405a-8c41-4b20-a21d-6f3569b51f7f)

Select the ZIP file you downloaded in Step 2.

![image](https://github.com/m5stack/M5CoreS3/assets/243476/d059625b-e593-4017-84e1-84c40cdc1e45)

## 4. Build

![image](https://github.com/m5stack/M5CoreS3/assets/243476/9d54861c-516b-49df-afd5-71a24a36e0dd)

**Comment by richstokes** [comment]
Thank you! this fixed it for me, too. The one installed via the package manager is broken.

**Comment by ropg** [comment]
OK, some stuff now works. Sadly no example how to talk to the touch screen, some examples do not compile and boy these people hate documentation and clarity.

**Comment by Tinyu-Zhao** [comment]
> OK, some stuff now works. Sadly no example how to talk to the touch screen, some examples do not compile and boy these people hate documentation and clarity.好的，现在一些东西可以运行。可惜没有关于如何与触摸屏交互的示例，有些示例无法编译，这些人讨厌文档和清晰度。

Add it.
https://github.com/m5stack/M5CoreS3/blob/9e73b0a61e91e7270850a0ca56c041f58cc108d3/examples/Basic/button/button.ino
