### ISSUE TITLE
PoweModeSet

### ISSUE THREAD

**Issue by d4rkdpg** [m5stack/M5CoreS3#59]
### Describe the bug

Hi can you please tell me how to call powerModeSet, I have a DMX module and when I used 12v in the display wont turn on, keeps power cycling. thanks.  Im using the latest version of the library.

### To reproduce

. 

### Expected behavior

to work with DMX module with 12v input. 

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by d4rkdpg** [comment]
any update on this?

**Comment by d4rkdpg** [comment]
can someone assist with this?

**Comment by imliubo** [comment]
Hi,
Sorry for the repley late, please check [this](https://github.com/m5stack/M5Module-DMX512/issues/4#issuecomment-2119255595).

**Comment by d4rkdpg** [comment]
HI i tried that, its working, although Im using CoreS3.begin(); specifically, do you have something for this also?

**Comment by imliubo** [comment]
actually, CoreS3.begin() is call M5.begin() in the internal, so use M5.begin() is same.

**Comment by d4rkdpg** [comment]
ok thanks
