### ISSUE TITLE
Make a Link

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [m5stack/M5CoreS3#62]
### Describe the bug

https://github.com/espressif/esp-bsp/issues/346
link to the Espressif BSP for all those who want to use ESP-IDF instead of Arduino. 

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Thanks for the reminder, I've [added it](https://github.com/m5stack/M5CoreS3?tab=readme-ov-file#start-with-board-support-package).
